### 模块一：Tensor 的创建与属性 ✨
这部分将带您熟悉创建张量的各种方式，并了解如何查看它们的基本属性。

#### 1. 导入 PyTorch (★☆☆)
任务: 导入 torch 和 numpy 库，并打印各自的版本号，这是使用 PyTorch 的第一步。

In [55]:
# 导入 torch 和 numpy 库
import torch
import numpy as np

# 打印导入成功信息和版本号
print(f"PyTorch 版本: {torch.__version__}")
print(f"NumPy 版本: {np.__version__}")

PyTorch 版本: 2.5.1+cu121
NumPy 版本: 1.26.4


#### 2. 从 Python 列表与 NumPy 数组创建 (★☆☆)
任务: 将一个 Python 列表 [[1, 2], [3, 4]] 和一个 NumPy 数组 np.array([[5, 6], [7, 8]]) 分别转换为 Tensor。

In [56]:
# 定义一个 Python 列表
data = [[1, 2], [3, 4]]
# 创建一个 NumPy 数组
np_arr = np.array([[5, 6], [7, 8]])

# 从列表创建
X = torch.tensor(data)
# 从 NumPy 数组创建 (注意：会共享内存)
Y = torch.from_numpy(np_arr)

print("--- 从列表创建的 Tensor ---")
print(X)
print("\n--- 从 NumPy 创建的 Tensor ---")
print(Y)

--- 从列表创建的 Tensor ---
tensor([[1, 2],
        [3, 4]])

--- 从 NumPy 创建的 Tensor ---
tensor([[5, 6],
        [7, 8]])


#### 3. 创建常量 Tensor (★☆☆)
任务: 创建三个形状均为 (2, 3) 的张量：一个全零张量，一个全一张量，以及一个所有元素均为常数 7 的张量。

In [57]:
# 定义形状
shape = (2, 3)

# 创建全零、全一、全为7的张量
t_zeros = torch.zeros(shape)
t_ones = torch.ones(shape)
t_sevens = torch.full(shape, 7)

print("--- 全零 Tensor ---")
print(t_zeros)
print("\n--- 全一 Tensor ---")
print(t_ones)
print("\n--- 填充为 7 的 Tensor ---")
print(t_sevens)

--- 全零 Tensor ---
tensor([[0., 0., 0.],
        [0., 0., 0.]])

--- 全一 Tensor ---
tensor([[1., 1., 1.],
        [1., 1., 1.]])

--- 填充为 7 的 Tensor ---
tensor([[7, 7, 7],
        [7, 7, 7]])


#### 4. 获取 Tensor 的核心属性 (★☆☆)
任务: 对于给定的张量 X = torch.tensor([[1.0, 2.0], [3.0, 4.0]])，一次性打印出它的形状 (shape)、数据类型 (dtype) 和所在设备 (device)。

In [58]:
# 创建一个示例张量
X = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# 获取并打印核心属性
print(f"--- Tensor 的核心属性 ---")
print(f"形状 (Shape): {X.shape}")
print(f"数据类型 (dtype): {X.dtype}")
print(f"所在设备 (device): {X.device}")

--- Tensor 的核心属性 ---
形状 (Shape): torch.Size([2, 2])
数据类型 (dtype): torch.float32
所在设备 (device): cpu


#### 5. 创建指定数据类型的 Tensor (★☆☆)
任务: 创建一个形状为 (2, 3)，数据类型为 torch.float16 (半精度浮点) 的全一 Tensor，并验证其数据类型。

In [59]:
# 定义形状和目标数据类型
shape = (2, 3)
dtype = torch.float16

# 在创建时通过 dtype 参数指定数据类型
Y = torch.ones(shape, dtype=dtype)

print(f"--- 创建的 Tensor ---")
print(Y)
print(f"\n--- 验证其数据类型 ---")
print(Y.dtype)

--- 创建的 Tensor ---
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

--- 验证其数据类型 ---
torch.float16


#### 6. 仿照其他 Tensor 创建新 Tensor (★☆☆)
任务: 给定一个已存在的源张量 src，它的值为 [[1, 2, 3], [4, 5, 6]] 且类型为 float16，请创建一个与它属性（形状、类型、设备）都相同，但值为全零的新 Tensor。

In [60]:
# 定义一个源张量
src = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float16)

# 使用 _like 函数可以方便地复制属性
Z = torch.zeros_like(src)

print("--- 源 Tensor ---")
print(src)
print(f"属性: {src.shape}, {src.dtype}, {src.device}")
print("\n--- 仿照创建的全零 Tensor ---")
print(Z)
print(f"属性: {Z.shape}, {Z.dtype}, {Z.device}")

--- 源 Tensor ---
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)
属性: torch.Size([2, 3]), torch.float16, cpu

--- 仿照创建的全零 Tensor ---
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
属性: torch.Size([2, 3]), torch.float16, cpu


#### 7. 创建不同分布的随机 Tensor (★☆☆)
任务: 创建两个形状均为 (3, 3) 的随机 Tensor：X 的元素在 [0, 1) 区间均匀分布，Y 的元素服从标准正态分布（均值为0，方差为1）。

In [61]:
# 设置随机种子以保证结果可复现
torch.manual_seed(42)

# 定义形状
shape = (3, 3)

# 创建不同分布的随机张量
X = torch.rand(shape)  # 均匀分布
Y = torch.randn(shape) # 标准正态分布

print(f"--- [0, 1) 均匀分布随机 Tensor ---")
print(X)
print(f"\n--- 标准正态分布随机 Tensor ---")
print(Y)


--- [0, 1) 均匀分布随机 Tensor ---
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

--- 标准正态分布随机 Tensor ---
tensor([[ 1.5231,  0.6647, -1.0324],
        [-0.2770, -0.1671, -0.1079],
        [-1.4285, -0.2810,  0.7489]])


#### 8. 创建序列 Tensor (★☆☆)
任务: 创建两个序列 Tensor：X 是一个从 0 到 10（不含10）、步长为1的整数序列；Y 是一个从 0 到 1（包含1）、均匀划分成5个元素的浮点数序列。

In [62]:
# 使用 arange 创建整数序列 (不含结束点)
X = torch.arange(0, 10)

# 使用 linspace 创建等差序列 (包含结束点)
# 参数: start, end, steps
Y = torch.linspace(0, 1, 5)

print("--- arange 创建的整数序列 ---")
print(X)
print("\n--- linspace 创建的等差序列 ---")
print(Y)

--- arange 创建的整数序列 ---
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

--- linspace 创建的等差序列 ---
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


#### 9. 在指定设备上创建 Tensor (★★☆)
任务: 检查您的环境中 CUDA (GPU) 是否可用，如果可用，则在第一个 GPU (cuda:0) 上创建一个 2x2 的全一张量；否则，在 CPU 上创建。

In [63]:
# 检查 CUDA 是否可用
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# 使用 device 参数在指定设备上创建张量
Z = torch.ones(2, 2, device=device)

print(f"\n--- 创建的 Tensor ---")
print(Z)
print(f"它所在的设备是: {Z.device}")


--- 创建的 Tensor ---
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
它所在的设备是: cuda:0


### 模块二：索引、切片与形状变换 🔪
掌握了如何创建 Tensor 后，下一步是学习如何灵活地访问和重塑它们。这是数据预处理和特征工程中的核心技能。

#### 10. 基础索引：访问特定元素 (★☆☆)
任务: 创建一个 3x3 的序列张量 X，其值为 0 到 8。然后，访问并打印出位于第 2 行、第 1 列的元素（注意索引从0开始）。

In [64]:
# 创建一个 3x3 的张量
X = torch.arange(9).reshape(3, 3)

# 访问第 2 行 (索引为1), 第 1 列 (索引为0) 的元素
element = X[1, 0]

print("--- 原始 Tensor ---")
print(X)
print(f"\n--- 第2行、第1列的元素是 ---")
print(element)

--- 原始 Tensor ---
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

--- 第2行、第1列的元素是 ---
tensor(3)


#### 11. 基础切片：提取整行与整列 (★☆☆)
任务: 对于一个 4x4 的序列张量 Y（值为0-15），提取并打印出它的第 3 整行和第 4 整列。

In [65]:
# 创建一个 4x4 的张量
Y = torch.arange(16).reshape(4, 4)

# 提取第 3 行 (索引为2)
third_row = Y[2, :] # 或者 Y[2]

# 提取第 4 列 (索引为3)
fourth_col = Y[:, 3]

print("--- 原始 Tensor ---")
print(Y)
print("\n--- 第 3 行 ---")
print(third_row)
print("\n--- 第 4 列 ---")
print(fourth_col)

--- 原始 Tensor ---
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

--- 第 3 行 ---
tensor([ 8,  9, 10, 11])

--- 第 4 列 ---
tensor([ 3,  7, 11, 15])


#### 12. 进阶切片：提取子矩阵 (★☆☆)
任务: 对于一个 5x5 的序列张量 Z（值为0-24），提取出由第3、4行和第2、3、4列共同构成的 2x3 子矩阵。

In [66]:
# 创建一个 5x5 的张量
Z = torch.arange(25).reshape(5, 5)

# 提取子矩阵：行索引为 2, 3；列索引为 1, 2, 3
sub_matrix = Z[2:4, 1:4]

print("--- 原始 Tensor ---")
print(Z)
print("\n--- 提取的 2x3 子矩阵 ---")
print(sub_matrix)

--- 原始 Tensor ---
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

--- 提取的 2x3 子矩阵 ---
tensor([[11, 12, 13],
        [16, 17, 18]])


#### 13. 布尔索引：筛选满足条件的元素 (★☆☆)
任务: 创建一个 4x4 的随机整数张量 X（值在0-9之间），筛选出所有大于5的元素。

In [67]:
# 设置随机种子以保证结果可复现
torch.manual_seed(10)

# 创建一个 4x4 的随机整数张量
X = torch.randint(0, 10, (4, 4))

# 创建布尔掩码 (Mask)
mask = X > 5

# 使用掩码进行索引，筛选出符合条件的元素
filtered_elements = X[mask]

print("--- 原始 Tensor ---")
print(X)
print("\n--- 大于 5 的元素 ---")
print(filtered_elements)

--- 原始 Tensor ---
tensor([[7, 5, 2, 7],
        [2, 5, 7, 2],
        [1, 5, 6, 3],
        [1, 0, 6, 3]])

--- 大于 5 的元素 ---
tensor([7, 7, 7, 6, 6])


#### 14. 使用布尔索引进行原地修改 (★☆☆)
任务: 创建一个 3x4 的标准正态分布随机张量 Y，然后将其中所有小于0的元素都原地修改为0（这类似于ReLU激活函数的操作）。

In [68]:
# 设置随机种子
torch.manual_seed(20)

# 创建一个 3x4 的随机张量
Y = torch.randn(3, 4)
print("--- 原始 Tensor ---")
print(Y)

# 使用布尔索引找到小于0的元素，并原地赋值为0
Y[Y < 0] = 0

print("\n--- 修改后的 Tensor ---")
print(Y)

--- 原始 Tensor ---
tensor([[-1.2061,  0.0617,  1.1632, -1.5008],
        [-1.5944, -0.0187, -2.1325, -0.5270],
        [-0.1021,  0.0099, -0.4454, -1.4976]])

--- 修改后的 Tensor ---
tensor([[0.0000, 0.0617, 1.1632, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0099, 0.0000, 0.0000]])


#### 15. 改变形状 (★☆☆)
任务: 创建一个值为 0-11 的一维张量 Z，然后将其形状变为 3x4。请分别使用两种不同的方法实现。

In [69]:
# 创建一个一维张量
Z = torch.arange(12)

# 使用 .view() 改变形状
# .view() 要求原始张量的内存是连续的
Z_view = Z.view(3, 4)

# 使用 .reshape() 改变形状
# .reshape() 更灵活，如果内存不连续，它会先创建副本再改变形状
Z_reshape = Z.reshape(3, 4)

print("--- 原始 Tensor ---")
print(Z)
print("\n--- 使用 .view() 的结果 ---")
print(Z_view)
print("\n--- 使用 .reshape() 的结果 ---")
print(Z_reshape)

--- 原始 Tensor ---
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

--- 使用 .view() 的结果 ---
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

--- 使用 .reshape() 的结果 ---
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


#### 16. 增加维度 (★☆☆)
任务: 创建一个形状为 (3, 4) 的张量 X。在第1个维度（dim=0）和第3个维度（dim=2）上增加一个新维度，使其最终形状变为 (1, 3, 1, 4)。

In [70]:
# 创建一个 3x4 的张量
X = torch.arange(12).reshape(3, 4)
print(f"--- 原始 Tensor (shape: {X.shape}) ---")
print(X)

# 在第 1 个维度 (dim=0) 增加维度
X_unsqueezed_1 = X.unsqueeze(0)
print(f"\n--- 在 dim=0 unsqueeze 后 (shape: {X_unsqueezed_1.shape}) ---")

# 在第 3 个维度 (dim=2) 增加维度
X_unsqueezed_2 = X_unsqueezed_1.unsqueeze(2)
print(f"--- 在 dim=2 unsqueeze 后 (shape: {X_unsqueezed_2.shape}) ---")

--- 原始 Tensor (shape: torch.Size([3, 4])) ---
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

--- 在 dim=0 unsqueeze 后 (shape: torch.Size([1, 3, 4])) ---
--- 在 dim=2 unsqueeze 后 (shape: torch.Size([1, 3, 1, 4])) ---


#### 17. 压缩维度 (★☆☆)
任务: 创建一个形状为 (1, 3, 1, 2) 的随机张量 Y，移除所有大小为1的维度，使其最终形状变为 (3, 2)。

In [71]:
# 创建一个包含冗余维度的张量
Y = torch.rand(1, 3, 1, 2)

# 使用 .squeeze() 移除所有大小为1的维度
Y_squeezed = Y.squeeze()

print(f"--- 原始 Tensor (shape: {Y.shape}) ---")
print(Y)
print(f"\n--- squeeze 后的 Tensor (shape: {Y_squeezed.shape}) ---")
print(Y_squeezed)

--- 原始 Tensor (shape: torch.Size([1, 3, 1, 2])) ---
tensor([[[[0.4489, 0.2113]],

         [[0.6839, 0.7478]],

         [[0.4627, 0.7742]]]])

--- squeeze 后的 Tensor (shape: torch.Size([3, 2])) ---
tensor([[0.4489, 0.2113],
        [0.6839, 0.7478],
        [0.4627, 0.7742]])


#### 18. 交换维度 (★☆☆)
任务: 在深度学习中，图像张量通常以 (C, H, W)（通道, 高, 宽）格式存储。请创建一个形状为 (3, 224, 224) 的模拟图像张量 Z，并将其维度转换为 (H, W, C)，以方便图像显示，可以尝试多种方法。

In [72]:
# 创建一个模拟图像张量 (通道, 高, 宽)
C, H, W = 3, 224, 224
Z = torch.randn(C, H, W)

# 使用 .permute() 交换维度
# 将 (0, 1, 2) -> (1, 2, 0)
Z_permuted = Z.permute(1, 2, 0)

# 使用 .transpose() 交换维度
Z_transpose = Z.transpose(0, 1).transpose(1, 2)


print(f"--- 原始 Tensor 形状 (C, H, W) ---")
print(Z.shape)
print(f"\n--- permute 后的 Tensor 形状 (H, W, C) ---")
print(Z_permuted.shape)
print(f"\n--- transpose 后的 Tensor 形状 (H, W, C) ---")
print(Z_transpose.shape)

--- 原始 Tensor 形状 (C, H, W) ---
torch.Size([3, 224, 224])

--- permute 后的 Tensor 形状 (H, W, C) ---
torch.Size([224, 224, 3])

--- transpose 后的 Tensor 形状 (H, W, C) ---
torch.Size([224, 224, 3])


#### 19. 沿现有维度拼接张量 (★☆☆)
任务: 创建两个形状均为 (2, 3) 的张量 X ∈ [0,6) 和 Y ∈ [6,12)。将它们分别沿维度0（行方向）和维度1（列方向）进行拼接。

In [73]:
# 创建两个 2x3 的张量
X = torch.arange(6).reshape(2, 3)
Y = torch.arange(6, 12).reshape(2, 3)

# 沿维度0 (行) 拼接
cat_dim0 = torch.cat((X, Y), dim=0)

# 沿维度1 (列) 拼接
cat_dim1 = torch.cat((X, Y), dim=1)

print("--- 原始 Tensor X ---")
print(X)
print("\n--- 原始 Tensor Y ---")
print(Y)
print("\n--- 沿 dim=0 拼接 (结果形状: 4x3) ---")
print(cat_dim0)
print("\n--- 沿 dim=1 拼接 (结果形状: 2x6) ---")
print(cat_dim1)

--- 原始 Tensor X ---
tensor([[0, 1, 2],
        [3, 4, 5]])

--- 原始 Tensor Y ---
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

--- 沿 dim=0 拼接 (结果形状: 4x3) ---
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

--- 沿 dim=1 拼接 (结果形状: 2x6) ---
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


#### 20. 沿新维度堆叠张量 (★☆☆)
任务: 创建两个形状均为 (2, 3) 的张量 X 和 Y。将它们堆叠起来，创建一个新的维度，使结果张量的形状变为 (2, 2, 3)。

In [74]:
# 重新创建两个 2x3 的张量
X = torch.arange(6).reshape(2, 3)
Y = torch.arange(6, 12).reshape(2, 3)

# 沿一个新维度 (dim=0) 进行堆叠
stacked_tensor = torch.stack((X, Y), dim=0)

print("--- 原始 Tensor X (shape: 2x3) ---")
print(X)
print("\n--- 原始 Tensor Y (shape: 2x3) ---")
print(Y)
print("\n--- 堆叠后的 Tensor (结果形状: 2x2x3) ---")
print(stacked_tensor)
print(f"堆叠后形状: {stacked_tensor.shape}")


--- 原始 Tensor X (shape: 2x3) ---
tensor([[0, 1, 2],
        [3, 4, 5]])

--- 原始 Tensor Y (shape: 2x3) ---
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

--- 堆叠后的 Tensor (结果形状: 2x2x3) ---
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
堆叠后形状: torch.Size([2, 2, 3])


#### 21. 分割张量：精确控制与便捷分割 (★★☆)
任务: 对一个7x4的张量Z，将其沿行（dim=0）均匀分割成2块（可以尝试两种方法），再将第一个块其沿行（dim=0）分割成不等大小的块[1,3]，PyTorch会自动处理不能整除的情况

In [75]:
Z = torch.arange(28).reshape(7, 4)
print("--- 用于分割的原始 Tensor (7x4) ---")
print(Z)

# 将张量沿 dim=0 分割成大小分别为2块
chunks = torch.chunk(Z, 2, dim=0)
print("--- chunk 分割成的2个块 ---")
print(chunks)

# 将张量沿 dim=0 分割成大小分别为2块(这里的4指的是每块大小为4)
splits = torch.split(Z, 4, dim=0)
print("--- split 分割成的2个块 ---")
print(splits)

# 将第一个块沿 dim=0 分割成不等大小的块
unequal_chunks = torch.split(chunks[0], [1, 3], dim=0)
print("--- split 分割成不等大小的块 (分别为1, 3行) ---")
print(unequal_chunks)


--- 用于分割的原始 Tensor (7x4) ---
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]])
--- chunk 分割成的2个块 ---
(tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), tensor([[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]]))
--- split 分割成的2个块 ---
(tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), tensor([[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]]))
--- split 分割成不等大小的块 (分别为1, 3行) ---
(tensor([[0, 1, 2, 3]]), tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))


#### 22. 综合运用：重塑与拼接 (★★☆)
任务: 假设你有一个批次的数据 (Batch, Features)，形状为 (4, 10)。你需要将其分成两组，每组2个样本，分别进行不同的处理（这里可以用乘以不同常数模拟×2 or ×3），然后再将处理后的结果合并起来。

In [76]:
torch.manual_seed(10)
# 创建一个模拟的批次数据
batch_data = torch.randint(0, 10, (4, 10))

# 1. 将数据分割成两组
group1, group2 = torch.chunk(batch_data, 2, dim=0)

# 2. 模拟对两组数据进行不同的处理
processed_group1 = group1 * 2
processed_group2 = group2 * 3

# 3. 将处理后的结果重新拼接成一个批次
final_batch = torch.cat((processed_group1, processed_group2), dim=0)

print("--- 原始批次数据 (4x10) ---")
print(batch_data.shape)
print(batch_data)
print("\n--- 分割后的两组 (均为 2x10) ---")
print(f"组1形状: {group1.shape}, 组2形状: {group2.shape}")
print(group1)
print(group2)
print("\n--- 重新拼接后的最终批次 (4x10) ---")
print(final_batch.shape)
print(final_batch)

--- 原始批次数据 (4x10) ---
torch.Size([4, 10])
tensor([[7, 5, 2, 7, 2, 5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6, 3, 4, 0, 6, 2],
        [8, 9, 2, 0, 9, 9, 4, 4, 9, 4],
        [4, 5, 4, 0, 8, 9, 3, 0, 9, 3]])

--- 分割后的两组 (均为 2x10) ---
组1形状: torch.Size([2, 10]), 组2形状: torch.Size([2, 10])
tensor([[7, 5, 2, 7, 2, 5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6, 3, 4, 0, 6, 2]])
tensor([[8, 9, 2, 0, 9, 9, 4, 4, 9, 4],
        [4, 5, 4, 0, 8, 9, 3, 0, 9, 3]])

--- 重新拼接后的最终批次 (4x10) ---
torch.Size([4, 10])
tensor([[14, 10,  4, 14,  4, 10, 14,  4,  2, 10],
        [12,  6,  2,  0, 12,  6,  8,  0, 12,  4],
        [24, 27,  6,  0, 27, 27, 12, 12, 27, 12],
        [12, 15, 12,  0, 24, 27,  9,  0, 27,  9]])
